### ISSUE TITLE
syntax error enigma .fileless uac bypass.....

### ISSUE THREAD

**Issue by mateo24xx** [r00t-3xp10it/msf-auxiliarys#6]
/usr/share/metasploit-framework/modules/post/windows/escalate/enigma_fileless_uac_bypass.rb: SyntaxError /usr/share/metasploit-framework/modules/post/windows/escalate/enigma_fileless_uac_bypass.rb:7: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/usr/share/metasploit-framework/modules/post/windows/escalate/enigma_fileless_uac_bypass.rb:8: syntax error, unexpected '<'
<html lang="en">
 ^
/usr/share/metasploit-framework/modules/post/windows/escalate/enigma_fileless_uac_bypass.rb:9: syntax error, unexpected '<'
  <head>
   ^
/usr/share/metasploit-framework/modules/post/windows/escalate/enigma_fileless_uac_bypass.rb:11: syntax error, unexpected '<'
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
   ^
/usr/share/metasploit-framework/modules/post/windows/escalate/enigma_fileless_uac_bypass.rb:11: syntax error, unexpected tIDENTIFIER, expecting end-of-input
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
---------------------------

**Comment by r00t-3xp10it** [comment]
hello bro ..
i have just now downloaded and installed this module under my new computer (x64 bits)
and it have loaded without any syntax errors, so maybee your download as completed with
some errors, and them loading the module it will present that error ...

**Comment by mateo24xx** [comment]
hi bro..thanks for your reply.
i dont now what create that error but i downloaded it again and ever thing work good now..
good continuation.
.

**Comment by r00t-3xp10it** [comment]
Thanks for your bug report ( its importante to me) hint: eventvwr as been
patched allready .. but my module allow you to use another vuln binary
insted of eventvwr ..

Check the advanced options ..

Em 20/11/2017 18:29, "fenom" <notifications@github.com> escreveu:
